# Site
name: "tkanimals.com"
title: "Taking Care Animals"
description: "We can judge the heart of a man by his treatment of animals!"
logo: 'assets/images/logo.png'
favicon: 'favicon.ico'
url: https://tkanimals.com
baseurl: https://tkanimals.com
allow_search_engine: false
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  huynhtroc:
    name: Nguyễn Trọng Huỳnh
    display_name: Trọng Huỳnh
    avatar: assets/images/author/trong-huynh.jpg
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: huynhnt135@gmail.com
    web: https://tkanimals.com
    twitter: https://twitter.com/huynhtroc
    description: "Taking Care Animals! We can judge the heart of a man by his treatment of animals!"
  phamhuong:
    name: Phạm Thị Hương
    display_name: Phạm Hương    
    avatar: assets/images/author/huongyka.jpg
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: phamthihuong2603@gmail.com
    web: https://tkanimals.com
    twitter: 
    description: "Taking Care Animals! We can judge the heart of a man by his treatment of animals!"

# social links
twitter_username: johndoe
github_username:  sujaykundu777
facebook_username: johndoe
linkedin_username: johndoe
behance_username: johndoe
instagram_username: johndoe
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 1295

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: huynhnt135@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
